apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      serviceAccountName: currencyservice
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.10.1
        ports:
        - name: grpc
          containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: 7000
        livenessProbe:
          grpc:
            port: 7000
      - name: envoy
        image: ghcr.io/cmendesce/server-app:latest
        env:
          - name: FAULT_PERCENTAGE
            value: "0"
          - name: BACKEND_PORT
            value: "7000"
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - name: grpc
    port: 7000
    targetPort: 10000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice